const actions = {
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    CHANGE_LANG: 'CHANGE_LANG',
    CHANGE_SEARCH_LOC: 'CHANGE_SEARCH_LOC',
    ON_SEARCH_INPUT: 'ON_SEARCH_INPUT',
    ON_FILTER_BY_SIZE_START: 'ON_FILTER_BY_SIZE_START',
    ON_FILTER_BY_SIZE_END: 'ON_FILTER_BY_SIZE_END',
    ON_FILTER_BY_PRICE_START: 'ON_FILTER_BY_PRICE_START',
    ON_FILTER_BY_PRICE_END: 'ON_FILTER_BY_PRICE_END',
    ON_FILTER_BY_CONDITION: 'ON_FILTER_BY_CONDITION',
    ON_FILTER_BY_TYPE: 'ON_FILTER_BY_TYPE',
    ON_SORT_BY: 'ON_SORT_BY',
    ON_CHANGE_CARD_VIEW: 'ON_CHANGE_CARD_VIEW',
    ON_CLEAR_FILTER: 'ON_CLEAR_FILTER'
};

export default actions;